### PR TITLE
Fix CSM shader binding

### PR DESCRIPTION
**Pull request by mgsx-dev**
This is an alternative to #127

before the fix : 
- was working on LWJGL2, LWJGL3 and GWT backends (with my forgiving NVidia driver)
- didn't work on LWJGL2 and GWT backends (with my integrated GPU drivers)
- didn't work for some users on GWT and TeaVM backends.

After the fix
- works now on LWJGL3 and GWT backends (with my integrated GPU drivers)
- no longer work with LWJGL2 backend

Note that i had to migrate desktop demo to LWJGL3 backend. And LWJGL2 support will be removed once merged (which is OK imho)

### CODE REVIEW

**Comment by xpenatan** [comment]
So this is GPU issue and not webgl ?

I tested on GWT the gdx-gltf demo with my alienware RTX 3070 ti and it have the same problems. 

When I toggle CSM the default model hide it self and start giving errors
image

**Comment by mgsx-dev** [comment]
@xpenatan yeah, depending on OS and hardware, GPU drivers could be more forgiven that some other setup. I always test stuff that i commit, so yes, it was working for me on both desktop and webgl. That's why i didn't noticed issues.

**Comment by MonstrousSoftware** [comment]
Cross-posted from #127:

I have tested your fix following the https://github.com/mgsx-dev/gdx-gltf/pull/128 modification but it doesn't work for Chrome with the default ANGLE backend.

It does work if you switch the Chrome ANGLE backend from default (=D3D11) to OpenGL. (Use chrome:://flags and search for ANGLE).

The problem is the array of samplers in the shader code (the arrays of Transforms and PCFClip work fine). I have even tried fetching the location of each individual array element (u_csmSamplers[0], u_csmSamplers[1], etc.) and setting the elements individually, but every time you get exactly the 'weird result' as shown in the discord thread. The console reports 'Internal D3D11 error: Error compiling dynamic pixel executable.'

A fix which resolves this both for html and teavm and regardless of the ANGLE backend is to have individual sampler uniforms (
uniform sampler2D u_csmSamplers0; uniform sampler2D u_csmSamplers1; etc. and setting their value individually.

**Comment by mgsx-dev** [comment]
fixed by https://github.com/mgsx-dev/gdx-gltf/issues/127

**Pull request closed without merging**
